version: '2'
services:
    shine-app:
        image: shine
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://shine-postgresql:5432/shine
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    shine-postgresql:
        extends:
            file: postgresql.yml
            service: shine-postgresql
